name: My first test site
favicon: null
layout_spectrum: 0.19177635479718447
typography_spectrum: 0.4960795836523175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8957506003789604
  lightness: 0.9349305229261518
  saturation: 0.06601673713885248
  rhythmicContrast: 0.45267383893951774
purpose: []
